### ISSUE TITLE
PreMailer.Net is unable to process the pseudo class/element '.awlist1 li:before' due to a limitation in CsQuery.

### ISSUE THREAD

**Issue by omrivm** [milkshakesoftware/PreMailer.Net#106]
Hi,
I want to use PreMailer.Net to strip css from html (for embedding).  .awlist1 li:before is important feature for me (i don't manufacture the html so i can't replace it with something else). there is a change you can support it in feature versions?

Thanks!
Omri

**Comment by mrboring** [comment]
Hi

I'm having similar issues:

```
PreMailer.Net is unable to process the pseudo class/element 'td:nth-child(2)' due to a limitation in CsQuery.
PreMailer.Net is unable to process the pseudo class/element 'tr:nth-child(even)' due to a limitation in CsQuery.
PreMailer.Net is unable to process the pseudo class/element 'tr:nth-child(odd)' due to a limitation in CsQuery.
```

Should Premailer/AngleSharp be able to handle this?

Thanks.

Alan

**Comment by martinnormark** [comment]
Apparently it is on the [unsupported list](https://github.com/milkshakesoftware/PreMailer.Net/blob/master/PreMailer.Net/PreMailer.Net/CssSelectorParser.cs#L197) - but it probably shouldn't be there since replacing CsQuery with AngleSharp in #76  I just need to make a few tests before changing it and cutting a new release.

**Comment by omrivm** [comment]
Thanks!

**Comment by monicajellybean** [comment]
Hi, Any idea when this will be fixed? At the moment, this issue is preventing me from using Zurb's Foundation for Emails .

**Comment by martinnormark** [comment]
Will take a look at it when I get time to cut a new release with the latest changes.

**Comment by GenZodd** [comment]
Is this library maintained anymore? Seems this issue is still in the code base so assuming the repo stopped being maintained.

**Comment by smkanadl** [comment]
Are you using the latest NuGet Package? I had in mind they moved away from CsQuery some time ago.

**Comment by smkanadl** [comment]
Are you using the latest NuGet Package? I had in mind they moved away from
CsQuery some time ago.

Todd <notifications@github.com> schrieb am Fr., 2. Feb. 2018, 17:45:

**Comment by GenZodd** [comment]
Yes, using the NuGet package (last updated 2 years ago) but still get this error. AngelSharp was the dependency it had to install but the code is still giving this error.

**Comment by Duke482132** [comment]
I have about 816 warnings like:
`PreMailer.Net is unable to process the pseudo class/element '.badge-primary[href]:focus' due to a limitation in CsQuery.` and only like 2% of styles went into html file, can I do anything about it?

**Comment by Simonl9l** [comment]
Hi

It's been a few months. I using CoreUI (a licensed CSS library) and am getting over 1500 of these. I obviously don't have any control over the css, and it works fine in browsers! Using PreMail would be a real benefit, as the CSS library is somewhat huge!.

`PreMailer.Net is unable to process the pseudo class/element '.c-legacy-theme a.bg-info:hover' due to a limitation in CsQuery.`

etc.

I'm running the 2.2 Nuget Package, that's pulling in AngleSharp 0.14.0.

is there any way to remediate this?

**Comment by Webreaper** [comment]
I'm also seeing this error, even with Premailer 2.7.2.... Would appreciate if anyone has tips....
