### ISSUE TITLE
What is the latest version that supports .NET 4.0?

### ISSUE THREAD

**Issue by pbrianmackey** [milkshakesoftware/PreMailer.Net#135]
I just tried installing PreMailer.Net v1.5.5.  The install failed against a class library type project set to .NET 4.  I upgraded the project to .NET 4.5 and the issue went away.

Error:

> Install failed. Rolling back...
> Package 'PreMailer.Net.1.5.5 : AngleSharp [0.9.9, )' does not exist in project 'Bgc.Web.Core'

Unfortunately, the legacy code cannot be upgraded past .NET 4.0 at this time.  What is the latest version I can use?  BONUS:  Are there any major defects I should be aware of going to production with said version?

**Comment by martinnormark** [comment]
The framework version was changed in https://github.com/milkshakesoftware/PreMailer.Net/commit/59123748c368659744111fc7932b86bce15a88d0#diff-7dd93c4af2bd2993b02e015117172276 when CsQuery was replaced with AngleSharp - which means [v1.4.3](https://github.com/milkshakesoftware/PreMailer.Net/tree/v1.4.3) should be compatible.

You can go through the [releases](https://github.com/milkshakesoftware/PreMailer.Net/releases) and see what was done since v1.4.3.

Biggest change is replacing CsQuery with AngleSharp which means CSS parsing in v1.4.3 has several shortcomings and a couple of bugs which were fixed by introducing AngleSharp - so you might hit a few speed bumps.
