### ISSUE TITLE
Any plans to move away from CSQuery?

### ISSUE THREAD

**Issue by burningice2866** [milkshakesoftware/PreMailer.Net#75]
Are there any plans to move away from CSQuery and maybe use AngleSharp instead? Would there be any interest if i would start working on a pull request that replaces CSQuery with AngleSharp?

**Comment by martinnormark** [comment]
I did not know of AngleSharp - it looks very solid. I haven't been actively looking to replace CSQuery, but since it has [a few](https://github.com/milkshakesoftware/PreMailer.Net/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+csquery) [shortcomings](https://github.com/milkshakesoftware/PreMailer.Net#notes) it is indeed worth switching, and it would be amazing it you submitted a PR :bow:

**Comment by martinnormark** [comment]
Closing this since #76 is merged. Will push a new version to Nu Get when #77 is fixed, or verified as not related to AngleSharp.
